/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import ConsultasSQL.QuerysDetalleVentas;
import ConsultasSQL.QuerysInventarioProductos;
import Controlador.Ventas;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author XxHunterxX
 */
public class CrearVentasProductos extends javax.swing.JFrame {
    private int paginaActual = 1;
    public static int totalPages = Ventas.NumeroPagesProductos("");
    /**
     * Creates new form CrearVentasClientes
     */
    public CrearVentasProductos() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Evita el cierre automático
        Ventas.MostrarInventario("", paginaActual, totalPages);
        PromptSupport.setPrompt("Buscar por producto y marca", jtBuscar);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductosVentas = new javax.swing.JTable();
        seguimiento1 = new javax.swing.JLabel();
        jtBuscar = new javax.swing.JTextField();
        Buscar = new javax.swing.JLabel();
        siguiente1 = new javax.swing.JButton();
        previo1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtProductosVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N#", "Marca", "Producto", "Precio Compra", "Precio Venta", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProductosVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProductosVentas);
        if (jtProductosVentas.getColumnModel().getColumnCount() > 0) {
            jtProductosVentas.getColumnModel().getColumn(0).setResizable(false);
            jtProductosVentas.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtProductosVentas.getColumnModel().getColumn(1).setPreferredWidth(160);
            jtProductosVentas.getColumnModel().getColumn(2).setPreferredWidth(160);
            jtProductosVentas.getColumnModel().getColumn(3).setResizable(false);
            jtProductosVentas.getColumnModel().getColumn(3).setPreferredWidth(70);
            jtProductosVentas.getColumnModel().getColumn(4).setPreferredWidth(70);
            jtProductosVentas.getColumnModel().getColumn(5).setPreferredWidth(70);
        }

        seguimiento1.setText("Pagina:");

        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });
        jtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBuscarKeyReleased(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Buscar.setForeground(new java.awt.Color(0, 0, 204));
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        Buscar.setText("Buscar");

        siguiente1.setBackground(new java.awt.Color(253, 253, 255));
        siguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/adelante.jpg"))); // NOI18N
        siguiente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1ActionPerformed(evt);
            }
        });

        previo1.setBackground(new java.awt.Color(253, 253, 255));
        previo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/atras.jpg"))); // NOI18N
        previo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        previo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previo1ActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(253, 253, 252));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/volver.jpg"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Ingresar productos a la venta");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(previo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(siguiente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seguimiento1)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previo1)
                    .addComponent(siguiente1)
                    .addComponent(seguimiento1))
                .addGap(25, 25, 25)
                .addComponent(btnVolver)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscarActionPerformed

    private void jtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyReleased
        String textoBusqueda = jtBuscar.getText();
        paginaActual = 1;
        totalPages = Ventas.NumeroPagesProductos(textoBusqueda);
        Ventas.MostrarInventario(textoBusqueda, paginaActual, totalPages);        
    }//GEN-LAST:event_jtBuscarKeyReleased

    private void previo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previo1ActionPerformed
        if (paginaActual > 1) {
            paginaActual--;
            String textoBusqueda = jtBuscar.getText();

            Ventas.MostrarInventario(textoBusqueda, paginaActual, totalPages);    
        }   
    }//GEN-LAST:event_previo1ActionPerformed

    private void siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1ActionPerformed
        totalPages = Ventas.NumeroPagesProductos(jtBuscar.getText());
        if (paginaActual < totalPages) {
            paginaActual++;
            String textoBusqueda = jtBuscar.getText();

           Ventas.MostrarInventario(textoBusqueda, paginaActual, totalPages);      
        }   
    }//GEN-LAST:event_siguiente1ActionPerformed

    private void jtProductosVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosVentasMouseClicked
           boolean val = true;
           int seleccion = jtProductosVentas.getSelectedRow();
           
           QuerysInventarioProductos inventarioProductos = Ventas.inventarioProductoses.get(seleccion);
           String valor = "0";
           do {       
        UIManager.put("OptionPane.yesButtonText", "Si");
        UIManager.put("OptionPane.noButtonText", "No");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
            valor = JOptionPane.showInputDialog(null, "Agregue la cantidad a vender","",JOptionPane.INFORMATION_MESSAGE);
            
            
            
            
                if (valor != null) {
                int cantidad = 0;
               try {
                   cantidad = Integer.parseInt(valor);
                   
                   if(!(cantidad > 0)){
                        JOptionPane.showMessageDialog(null, "La Cantidad no puede ser 0");
                        return;
                   }
                   
                   val = false;
               } catch (NumberFormatException e) {
                   val = true;
               }
               
            if (!val){
                val = false;
                if (inventarioProductos.getCantidad() >= cantidad){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "La cantidad no deber sobrepasar la existencia");
                    val = true;
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "La Cantidad es incorrecta");
                val = true;
            }

                } else {
                    return;
                }
            
            
           } while (val);
           
        
           QuerysDetalleVentas querysDetalleVentas = new QuerysDetalleVentas();
           querysDetalleVentas.setFk_producto(inventarioProductos.getId());
           querysDetalleVentas.setFk_ventas(0);
           querysDetalleVentas.setCantidad(Integer.parseInt(valor));
           querysDetalleVentas.setPrecio(inventarioProductos.getPrecio_venta());
           
           boolean existe = false;
           for(QuerysDetalleVentas detalleVentas :CrearVentas.lisDetalles ){
               if(detalleVentas.getFk_producto() == querysDetalleVentas.getFk_producto()){
                   existe = true;
                   
                   int suma = detalleVentas.getCantidad()+Integer.parseInt(valor);
                   
                   if(suma > inventarioProductos.getCantidad()){
                        JOptionPane.showMessageDialog(null, "La cantidad no deber sobrepasar la existencia");
                        return;
                   }
                   detalleVentas.setCantidad(suma);
               }
               
           }
           
           if(!existe){
           CrearVentas.lisDetalles.add(querysDetalleVentas); 
           }

           CrearVentas.rellenarTabla();
           this.dispose();
       
    }//GEN-LAST:event_jtProductosVentasMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVentasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVentasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVentasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVentasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearVentasProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtBuscar;
    public static javax.swing.JTable jtProductosVentas;
    private javax.swing.JButton previo1;
    public static javax.swing.JLabel seguimiento1;
    private javax.swing.JButton siguiente1;
    // End of variables declaration//GEN-END:variables
}
