/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Conexion.Conexion;
import ConsultasSQL.QuerysDetalleVentas;
import ConsultasSQL.QuerysVentas;
import Controlador.Clientes;
import Controlador.Ventas;
import static Vistas.MostrarVentas.totalPages;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author XxHunterxX
 */
public class CrearVentas extends javax.swing.JFrame {
    public static int cliente = 0;
    private static Conexion con = new Conexion();
    private static java.sql.Connection conexion = con.getConexion();
    private static PreparedStatement ps = null;
    
    public static List<QuerysDetalleVentas> lisDetalles = new ArrayList<>();
    
    /**
     * Creates new form CrearVentas
     */
    public CrearVentas() {
        initComponents();
        CrearVentas.lisDetalles = new ArrayList<>();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Evita el cierre automático
        setResizable(false);
        Date fechaActual = new Date();
        setLocationRelativeTo(null);
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        
        // Formatear la fecha utilizando el objeto SimpleDateFormat
        String fechaFormateada = formatoFecha.format(fechaActual);
        txtFecha.setText(fechaFormateada);
        
        
        txtNumFactura.setText(generarNumeroFactura());
        txtCai.setText(generarCodigoHexadecimal()); 
        
        PromptSupport.setPrompt("Dar click para seleccionar cliente", jtClientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbEliminarDetalle = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtClientes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlSubTotal = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jlImpuesto = new javax.swing.JLabel();
        txtCai = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDireccion = new javax.swing.JTextArea();
        txtFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Agregar venta");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("CAI:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Número de factura:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(253, 253, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardarfacturaN.jpg"))); // NOI18N
        btnGuardar.setText("Guardar Factura");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(253, 253, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelarr.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jtDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm.", "Nombre del producto", "Cantidad", "Precio de venta", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDetallesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDetalles);
        if (jtDetalles.getColumnModel().getColumnCount() > 0) {
            jtDetalles.getColumnModel().getColumn(0).setMinWidth(50);
            jtDetalles.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtDetalles.getColumnModel().getColumn(0).setMaxWidth(50);
            jtDetalles.getColumnModel().getColumn(1).setMinWidth(250);
            jtDetalles.getColumnModel().getColumn(1).setPreferredWidth(250);
            jtDetalles.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jButton1.setBackground(new java.awt.Color(253, 253, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/NNN.jpg"))); // NOI18N
        jButton1.setText("Agregar productos a la venta");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Sub Total:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Impuesto:");

        jbEliminarDetalle.setText("Eliminar producto");
        jbEliminarDetalle.setEnabled(false);
        jbEliminarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarDetalleActionPerformed(evt);
            }
        });

        jLabel8.setText("Productos:");

        jtClientes.setEditable(false);
        jtClientes.setFocusable(false);
        jtClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesMouseClicked(evt);
            }
        });
        jtClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtClientesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Fecha:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Total:");

        jlSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlSubTotal.setText("0.00");

        jlTotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTotal.setText("0.00");

        jlImpuesto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlImpuesto.setText("0.00");

        txtCai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCai.setText("CAI");
        txtCai.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtNumFactura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNumFactura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNumFactura.setText("001-002-00-00000020");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Dirección:");

        jtDireccion.setEditable(false);
        jtDireccion.setBackground(new java.awt.Color(253, 253, 255));
        jtDireccion.setColumns(20);
        jtDireccion.setRows(5);
        jScrollPane2.setViewportView(jtDireccion);

        txtFecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtFecha.setText("2023-11-21");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbEliminarDetalle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jlSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jlImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(6, 6, 6)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCai, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(183, 183, 183)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumFactura))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEliminarDetalle)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jlSubTotal))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlImpuesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTotal)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(176, 176, 176))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CrearVentasProductos productos = new CrearVentasProductos();
        productos.setVisible(true);
        productos.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int desicion = JOptionPane.showConfirmDialog(rootPane, "Desea descartar la venta de estos productos");
        if(desicion == JOptionPane.YES_OPTION){
            CrearVentas.lisDetalles.clear();
            CrearVentas.rellenarTabla(); 
        } 
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        
            
        if(jtClientes.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente para la venta");
             return;
        }
        
        UIManager.put("OptionPane.yesButtonText", "Si");
        UIManager.put("OptionPane.noButtonText", "No");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        
        int desicion = JOptionPane.showConfirmDialog(null, "Desea agregar este producto de la ventana","",JOptionPane.WARNING_MESSAGE);
        if(desicion == JOptionPane.YES_OPTION){
            if (!CrearVentas.lisDetalles.isEmpty()) {
                
                QuerysVentas ventas = new QuerysVentas();
                ventas.setCai(txtCai.getText());
                ventas.setFecha(txtFecha.getText());
                ventas.setNumeroFactura(txtNumFactura.getText());
                ventas.setFk_cliente(CrearVentas.cliente);
                ventas.setImpuestos(Double.parseDouble(jlImpuesto.getText().replace(',', '.')));
                ventas.setTotal(Double.parseDouble(jlTotal.getText().replace(',', '.')));

                Ventas.Guardar(ventas, CrearVentas.lisDetalles);
             
                JOptionPane.showMessageDialog(null, "Venta ingresada exitosamente");
                CrearVentas.lisDetalles.clear();
                Ventas.MostrarVentas("", 1, Clientes.NumeroPages(""),null,null);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No hay detalles para la venta", "Error al guardar",
                        JOptionPane.OK_OPTION);
            }
        } 

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtClientesActionPerformed

    }//GEN-LAST:event_jtClientesActionPerformed

    private void jtClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesMouseClicked
        CrearVentasClientes crearVentas = new CrearVentasClientes();
        crearVentas.setVisible(true);
        crearVentas.setLocationRelativeTo(null);
    }//GEN-LAST:event_jtClientesMouseClicked

    private void jtDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDetallesMouseClicked
       int selet = jtDetalles.getSelectedRow();
       jbEliminarDetalle.setEnabled(true);
    }//GEN-LAST:event_jtDetallesMouseClicked

    private void jbEliminarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarDetalleActionPerformed
        UIManager.put("OptionPane.yesButtonText", "Si");
        UIManager.put("OptionPane.noButtonText", "No");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        int desicion = JOptionPane.showConfirmDialog(rootPane, "Desea descartar este producto de la venta","",JOptionPane.INFORMATION_MESSAGE);
        if(desicion == JOptionPane.YES_OPTION){
            int select = jtDetalles.getSelectedRow();
            
            
            CrearVentas.lisDetalles.remove(select);
            CrearVentas.rellenarTabla(); 
        } 
         jbEliminarDetalle.setEnabled(false);
    }//GEN-LAST:event_jbEliminarDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearVentas().setVisible(true);
            }
        });
    }
    
    public static String generarNumeroFactura() {
        String ultimoNumero = "00000000"; // Número por defecto si no se encuentra ningún registro en la base de datos

        try {
            // Consulta para obtener el último número de factura
            String consulta = "SELECT MAX(SUBSTRING(numeroFactura, 12, 8)) FROM ventas";

            ps = conexion.prepareStatement(consulta);
            ResultSet resultSet = ps.executeQuery();

            // Obtener el último número de factura de la base de datos
            if (resultSet.next()) {
                String ultimoNumeroDB = resultSet.getString(1);
                if (ultimoNumeroDB != null) {
                    ultimoNumero = ultimoNumeroDB;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // Incrementar el número en 1
        int nuevoNumero = Integer.parseInt(ultimoNumero) + 1;
        String nuevoNumeroStr = String.format("%08d", nuevoNumero); // Formatear el número a 8 dígitos

        // Construir el número de factura con el formato requerido
        return "001-002-00-" + nuevoNumeroStr;
    }
    

    public static String generarCodigoHexadecimal() {
        Random random = new Random();
        StringBuilder sb = new StringBuilder();

        for (int i = 0; i < 32; i++) {
            if (i > 0 && i % 6 == 0) {
                sb.append('-');
            }

            int valor = random.nextInt(16); // Genera un número aleatorio entre 0 y F en hexadecimal
            String parteHexadecimal = Integer.toHexString(valor); // Convierte el número a formato hexadecimal
            sb.append(parteHexadecimal); // Agrega la parte hexadecimal al resultado
        }

        return sb.toString().toUpperCase(); // Devuelve el código hexadecimal en mayúsculas
    }
    
     public static void rellenarTabla() {
        //CrearVentas.lisDetalles;
         DefaultTableModel model = (DefaultTableModel) CrearVentas.jtDetalles.getModel();
        
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        int count = 1;
        double subtotal;
        double impuesto;
        double total = 0;
        String[] datos = new String[8];

            for ( QuerysDetalleVentas detalleVentas: CrearVentas.lisDetalles) {
                datos[0] = count + "";
                datos[1] = detalleVentas.getDatosProducto().getProducto();
                datos[2] = String.valueOf(detalleVentas.getCantidad());
                datos[3] = String.valueOf(detalleVentas.getDatosProducto().getPrecio_venta());
                datos[4] = String.valueOf(detalleVentas.getCantidad()*detalleVentas.getDatosProducto().getPrecio_venta());
                
                total+=detalleVentas.getCantidad()*detalleVentas.getDatosProducto().getPrecio_venta();
                model.addRow(datos);
                count++;
            }
        
       subtotal = total  - (total*0.15);
       impuesto = (total*0.15);
          
       CrearVentas.jlImpuesto.setText(String.format("%.2f", impuesto));
       CrearVentas.jlSubTotal.setText(String.format("%.2f", subtotal));
       CrearVentas.jlTotal.setText(String.format("%.2f", total));
         
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbEliminarDetalle;
    public static javax.swing.JLabel jlImpuesto;
    public static javax.swing.JLabel jlSubTotal;
    public static javax.swing.JLabel jlTotal;
    public static javax.swing.JTextField jtClientes;
    public static javax.swing.JTable jtDetalles;
    public static javax.swing.JTextArea jtDireccion;
    private javax.swing.JLabel txtCai;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtNumFactura;
    // End of variables declaration//GEN-END:variables
}
