/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import static Controlador.Citas.eliminarCita;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.prompt.PromptSupport;
/**
 *
 * @author PC
 */
public class MostrarCitas extends javax.swing.JPanel {
    private int paginaActual = 1;
    public static int totalPages;

    /**
     * Creates new form MostrarVistas
     */
    public MostrarCitas() {
        initComponents();
        
        PromptSupport.setPrompt("Busqueda por todos los campos ", txtBusqueda);
        tblMostraCitas.getTableHeader().setReorderingAllowed(false);
        totalPages = Controlador.Citas.NumeroPages("", paginaActual,Listadoempleados.getModel().getSelectedItem().toString());
        Controlador.Citas.MostrarCitas("", paginaActual, totalPages,Listadoempleados.getModel().getSelectedItem().toString());
        
        // ocultar la columna 1 id
        int columnIndex1 = 1; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostraCitas.getColumnModel().getColumn(columnIndex1).setMaxWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex1).setMinWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex1).setPreferredWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex1).setResizable(false);
        
        
        // ocultar la columna 2 Edad
        int columnIndex2 = 3; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostraCitas.getColumnModel().getColumn(columnIndex2).setMaxWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex2).setMinWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex2).setPreferredWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex2).setResizable(false);
        
        // ocultar la columna 10 notas
        int columnIndex3 = 9; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostraCitas.getColumnModel().getColumn(columnIndex3).setMaxWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex3).setMinWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex3).setPreferredWidth(0);
        tblMostraCitas.getColumnModel().getColumn(columnIndex3).setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostraCitas = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        siguiente = new javax.swing.JButton();
        Previo = new javax.swing.JButton();
        seguimiento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Listadoempleados = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCrear1 = new javax.swing.JButton();
        EditarTratamiento = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblMostraCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num", "Id", "Nombre ", "Tipo de cliente", "telefono", "Servicios", "Empleado", "Fecha", "Hora", "Notas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMostraCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostraCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostraCitas);

        txtBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        siguiente.setBackground(new java.awt.Color(253, 253, 255));
        siguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/adelante.jpg"))); // NOI18N
        siguiente.setBorder(null);
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        Previo.setBackground(new java.awt.Color(253, 253, 255));
        Previo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Previo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/atras.jpg"))); // NOI18N
        Previo.setBorder(null);
        Previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevioActionPerformed(evt);
            }
        });

        seguimiento.setText("Pagina: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel4.setText("Buscar ");

        Listadoempleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Corte", "Tratamiento", "Manicura y pedicura" }));
        Listadoempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoempleadosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Seleccionar Listado");

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Listado de citas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N

        btnCrear1.setBackground(new java.awt.Color(253, 253, 255));
        btnCrear1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregarN.jpg"))); // NOI18N
        btnCrear1.setText("Agregar ");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });

        EditarTratamiento.setBackground(new java.awt.Color(253, 253, 255));
        EditarTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editarN.jpg"))); // NOI18N
        EditarTratamiento.setText("Editar");
        EditarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarTratamientoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(253, 253, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Previo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(Listadoempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Listadoempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarTratamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seguimiento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Previo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void tblMostraCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostraCitasMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 2){
            int fila =tblMostraCitas.getSelectedRow();
            VerCita verCitas = new VerCita();
            
            verCitas.lblNombre.setText(tblMostraCitas.getValueAt(fila, 2).toString());
            verCitas.lbCliente.setText(tblMostraCitas.getValueAt(fila, 3).toString());
            verCitas.lblEmpleado.setText(tblMostraCitas.getValueAt(fila, 6).toString());
            verCitas.lbTelefono.setText(tblMostraCitas.getValueAt(fila, 4).toString());
            verCitas.lblServicio.setText(tblMostraCitas.getValueAt(fila, 5).toString());
            verCitas.lblFecha.setText(tblMostraCitas.getValueAt(fila, 7).toString());
            verCitas.lblHora.setText(tblMostraCitas.getValueAt(fila, 8).toString());
            verCitas.txtDescripcion.setText(tblMostraCitas.getValueAt(fila, 9).toString());
            
            verCitas.setVisible(true);
        }
    }//GEN-LAST:event_tblMostraCitasMouseClicked

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        String textoBusqueda = txtBusqueda.getText();
        Controlador.Citas.MostrarCitas(textoBusqueda, paginaActual, totalPages,Listadoempleados.getModel().getSelectedItem().toString());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        totalPages = Controlador.Citas.NumeroPages(txtBusqueda.getText(), paginaActual,Listadoempleados.getModel().getSelectedItem().toString());
        if (paginaActual < totalPages) {
            paginaActual++;
            Controlador.Citas.MostrarCitas(txtBusqueda.getText(), paginaActual, totalPages,Listadoempleados.getModel().getSelectedItem().toString());
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void PrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevioActionPerformed

        if (paginaActual > 1) {
            paginaActual--;
            Controlador.Citas.MostrarCitas(txtBusqueda.getText(), paginaActual, totalPages,Listadoempleados.getModel().getSelectedItem().toString());
        }
    }//GEN-LAST:event_PrevioActionPerformed

    private void ListadoempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoempleadosActionPerformed
        String  valor= Listadoempleados.getModel().getSelectedItem().toString();

        Controlador.Citas.MostrarCitas(txtBusqueda.getText(), paginaActual, totalPages,valor);
    }//GEN-LAST:event_ListadoempleadosActionPerformed

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        IngresarCita ing = new IngresarCita();
        ing.setVisible(true);
        
    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        //variable para seleccionar el producto de la lista de productos
        int fila = tblMostraCitas.getSelectedRow();

        // try catch para ejecutar las validaciones
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "No se seleccionó ningúna cita ",
                    "Error al eliminar", JOptionPane.WARNING_MESSAGE);
                return; // Salir del método si no se seleccionó ningún producto
            } else {
                int respuesta = JOptionPane.showConfirmDialog(null, "Deseas eliminar "
                    + "este registro?", "Advertencia", JOptionPane.YES_NO_OPTION);

                if (respuesta == JOptionPane.YES_OPTION) {
                    // Eliminar la citaseleccionado en la tabla
                    eliminarCita();
                    Controlador.Citas.MostrarCitas(txtBusqueda.getText(), paginaActual, totalPages,Listadoempleados.getModel().getSelectedItem().toString());
                    JOptionPane.showMessageDialog(null, "Registro eliminado exitosamente",
                        "Eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);

                }
                else {
                    
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void EditarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarTratamientoActionPerformed
        // Variable para seleccionar la cita de la tabla de citas
        int fila = tblMostraCitas.getSelectedRow();
        
        try {
            if(fila < 0){
                JOptionPane.showMessageDialog(null, "No se seleccionó ningúna cita",
                    "Error al editar", JOptionPane.WARNING_MESSAGE);
                 return;
            }else{
                String idCita = (String) tblMostraCitas.getValueAt(fila, 1);
                EditarCita edt = new EditarCita();
                edt.setVisible(true);
                edt.setLocationRelativeTo(null);
                Vistas.EditarCita.txtid.setText(idCita);
                
                
                //Vistas.EditarTratamiento.txtNombre.setText(tblMostrarTratamiento.getValueAt(fila, 2).toString());
                
                
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_EditarTratamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarTratamiento;
    public static javax.swing.JComboBox<String> Listadoempleados;
    public static javax.swing.JButton Previo;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel seguimiento;
    public static javax.swing.JButton siguiente;
    public static javax.swing.JTable tblMostraCitas;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
