/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Conexion.Conexion;
import ConsultasSQL.QuerysTratamiento;
import Controlador.Tratamiento;
//import static Vistas.EditarTratamiento.Label_Foto2;
//import static Vistas.IngresarTratamiento.JtListadoProductos;
import static Vistas.MostrarTratamientos.tblMostrarTratamiento;
import static Vistas.VerTratamiento.Label_Foto1;
import static Vistas.VerTratamiento.Label_Foto2;
import static Vistas.VerTratamiento.txtNombre;
import com.mysql.cj.jdbc.Blob;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;
import static Vistas.EditarTratamiento.tblProductosDeTratamiento;

/**
 *
 * @author PC
 */
public class MostrarTratamientos extends javax.swing.JPanel {
    
    private static Conexion con = new Conexion();
    private static Connection conexion = con.getConexion();
    private static PreparedStatement ps = null;
    
    
    
    public MostrarTratamientos() throws IOException {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tblMostrarTratamiento.getModel();
        model.setRowCount(0);
        Controlador.Tratamiento.MostrarTratamientos();
        
        
        
        
        // ocultar la columna 7 NombreProductos
        int columnIndex = 7; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex).setMaxWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex).setMinWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex).setPreferredWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex).setResizable(false);
        
        // ocultar la columna 5 Foto1
        int columnIndex2 = 5; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex2).setMaxWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex2).setMinWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex2).setPreferredWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex2).setResizable(false);
        
        // ocultar la columna 6 Foto2
        int columnIndex3 = 6; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex3).setMaxWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex3).setMinWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex3).setPreferredWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex3).setResizable(false);
        
        // ocultar la columna 1 id
        int columnIndex4 = 1; // Índice de la columna que deseas ocultar

        // Oculta la columna
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex4).setMaxWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex4).setMinWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex4).setPreferredWidth(0);
        tblMostrarTratamiento.getColumnModel().getColumn(columnIndex4).setResizable(false);
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarCortes = new javax.swing.JTable();
        btnCrear1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        siguiente = new javax.swing.JButton();
        Previo = new javax.swing.JButton();
        seguimiento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Listadoempleados = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarTratamiento = new javax.swing.JTable();
        btnCrear2 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        txtBusqueda1 = new javax.swing.JTextField();
        siguiente1 = new javax.swing.JButton();
        Previo1 = new javax.swing.JButton();
        seguimiento1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EditarTratamiento = new javax.swing.JButton();

        tblMostrarCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Num", "Nombre del corte", "Género", "Precio", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMostrarCortes);

        btnCrear1.setBackground(new java.awt.Color(255, 253, 252));
        btnCrear1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnCrear1.setText("Agregar ");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 253, 252));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        siguiente.setBackground(new java.awt.Color(253, 253, 252));
        siguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_delante.png"))); // NOI18N
        siguiente.setBorder(null);
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        Previo.setBackground(new java.awt.Color(253, 253, 252));
        Previo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Previo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_atras.png"))); // NOI18N
        Previo.setBorder(null);
        Previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevioActionPerformed(evt);
            }
        });

        seguimiento.setText("Pagina: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel4.setText("Buscar ");

        Listadoempleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Hombre", "Mujer" }));
        Listadoempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoempleadosActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccionar Listado");

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel6.setText("Listado de tipos de cortes de cabellos ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));

        //hacer que la tabla no sea editabe
        tblMostrarTratamiento.setFocusable(false);
        tblMostrarTratamiento = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblMostrarTratamiento.setAutoCreateRowSorter(true);
        tblMostrarTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Id", "Nombre del tratamiento", "Tipo de Tratamiento", "Descripción", "Foto 1", "Foto 2", "Nombre de los productos", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMostrarTratamiento.setToolTipText("");
        tblMostrarTratamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarTratamientoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMostrarTratamiento);
        if (tblMostrarTratamiento.getColumnModel().getColumnCount() > 0) {
            tblMostrarTratamiento.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        btnCrear2.setBackground(new java.awt.Color(255, 253, 252));
        btnCrear2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregarN.jpg"))); // NOI18N
        btnCrear2.setText("Agregar ");
        btnCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear2ActionPerformed(evt);
            }
        });

        btnEliminar1.setBackground(new java.awt.Color(255, 253, 252));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        txtBusqueda1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusqueda1ActionPerformed(evt);
            }
        });
        txtBusqueda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqueda1KeyReleased(evt);
            }
        });

        siguiente1.setBackground(new java.awt.Color(253, 253, 252));
        siguiente1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        siguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/adelante.jpg"))); // NOI18N
        siguiente1.setBorder(null);
        siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1ActionPerformed(evt);
            }
        });

        Previo1.setBackground(new java.awt.Color(253, 253, 252));
        Previo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Previo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/atras.jpg"))); // NOI18N
        Previo1.setBorder(null);
        Previo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Previo1ActionPerformed(evt);
            }
        });

        seguimiento1.setText("Pagina: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel5.setText("Buscar ");

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Listado de tratamientos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListaodologoBarberia.png"))); // NOI18N

        EditarTratamiento.setBackground(new java.awt.Color(255, 253, 252));
        EditarTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditarTratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editarN.jpg"))); // NOI18N
        EditarTratamiento.setText("Editar");
        EditarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarTratamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(345, 345, 345))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(131, 131, 131)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Previo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seguimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditarTratamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(txtBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCrear2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditarTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seguimiento1)
                    .addComponent(Previo1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed

    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
       
    }//GEN-LAST:event_siguienteActionPerformed

    private void PrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevioActionPerformed

       
    }//GEN-LAST:event_PrevioActionPerformed

    private void ListadoempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoempleadosActionPerformed
    }//GEN-LAST:event_ListadoempleadosActionPerformed

    private void btnCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear2ActionPerformed
        //Agregar un tratamiento
        IngresarTratamiento ingresarTratamiento = new IngresarTratamiento();
        ingresarTratamiento.setVisible(true);
        ingresarTratamiento.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnCrear2ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
      
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void txtBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusqueda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusqueda1ActionPerformed

    private void txtBusqueda1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqueda1KeyReleased
        
    }//GEN-LAST:event_txtBusqueda1KeyReleased

    private void siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1ActionPerformed
       
    }//GEN-LAST:event_siguiente1ActionPerformed

    private void Previo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Previo1ActionPerformed

    }//GEN-LAST:event_Previo1ActionPerformed

    private void tblMostrarTratamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarTratamientoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = tblMostrarTratamiento.getSelectedRow();
            if (filaSeleccionada >= 0) {
                String idTratamiento = (String) tblMostrarTratamiento.getValueAt(filaSeleccionada, 1); // Supongo que el ID está en la primera columna.
                VerTratamiento verTratamiento = null;
                try {
                    verTratamiento = new VerTratamiento(idTratamiento);
                } catch (IOException ex) {
                    //Logger.getLogger(MostrarCortes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
                verTratamiento.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_tblMostrarTratamientoMouseClicked

    private void EditarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarTratamientoActionPerformed
        // Variable para seleccionar el producto de la lista de productos
        int fila = tblMostrarTratamiento.getSelectedRow();
        
        try {
            if(fila < 0){
                JOptionPane.showMessageDialog(null, "No se seleccionó ningún tratamiento",
                    "Error al editar", JOptionPane.WARNING_MESSAGE);
                 return;
            }else{
                String idTratamiento = (String) tblMostrarTratamiento.getValueAt(fila, 1);
                EditarTratamiento edt = new EditarTratamiento(idTratamiento);
                edt.setVisible(true);
                edt.setLocationRelativeTo(null);
                Vistas.EditarTratamiento.txtId.setText(idTratamiento);
                
                
                //Vistas.EditarTratamiento.txtNombre.setText(tblMostrarTratamiento.getValueAt(fila, 2).toString());
                
                
            }
        } catch (Exception e) {
        }

        
    }//GEN-LAST:event_EditarTratamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarTratamiento;
    private javax.swing.JComboBox<String> Listadoempleados;
    public static javax.swing.JButton Previo;
    public static javax.swing.JButton Previo1;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnCrear2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel seguimiento;
    public static javax.swing.JLabel seguimiento1;
    public static javax.swing.JButton siguiente;
    public static javax.swing.JButton siguiente1;
    public static javax.swing.JTable tblMostrarCortes;
    public static javax.swing.JTable tblMostrarTratamiento;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtBusqueda1;
    // End of variables declaration//GEN-END:variables
}
