/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;
import Controlador.Devoluciones;

public class MostrarDevoluciones extends javax.swing.JPanel {
        private int paginaActual = 1;
    public static int totalPages ;
    public MostrarDevoluciones() {
        initComponents();
    
        tblMostrarDevoluciones.getTableHeader().setReorderingAllowed(false);
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String textoInicial;
        String textoFinal;
               try {
                    textoFinal = formato.format(FechaFinal.getDate());
               } catch (Exception e) {
                    textoFinal = null;
               }
                try {
                    textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
               } catch (Exception e) {
                    textoInicial = null;
               }
        Devoluciones.MostrarDevoluciones("", paginaActual, totalPages, textoInicial, textoFinal);
        PromptSupport.setPrompt("Buscar por la fecha, por descripción y por el número de factura", txtBusqueda);
      
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        seguimiento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarDevoluciones = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FechaInicio = new com.toedter.calendar.JDateChooser();
        FechaFinal = new com.toedter.calendar.JDateChooser();
        btnRecargar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Listado de devoluciones");

        txtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusLost(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(255, 255, 248));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_atras.png"))); // NOI18N
        btnAtras.setToolTipText("");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAdelante.setBackground(new java.awt.Color(255, 255, 248));
        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_delante.png"))); // NOI18N
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });

        seguimiento.setText("Pagina: ");

        tblMostrarDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num.", "Número de factura", "Descripción", "Fecha", "cantidad", "Precio", "SubTotal", "Monto rembolsado", "ID", "IdVentas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMostrarDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarDevolucionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMostrarDevoluciones);
        if (tblMostrarDevoluciones.getColumnModel().getColumnCount() > 0) {
            tblMostrarDevoluciones.getColumnModel().getColumn(0).setMinWidth(50);
            tblMostrarDevoluciones.getColumnModel().getColumn(0).setMaxWidth(50);
            tblMostrarDevoluciones.getColumnModel().getColumn(4).setMinWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(4).setMaxWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(5).setMinWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(5).setMaxWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(6).setMinWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(6).setMaxWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(8).setMinWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(8).setMaxWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(9).setMinWidth(0);
            tblMostrarDevoluciones.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel4.setText("Buscar:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Buscar por fecha:");

        FechaInicio.setToolTipText("a");
        FechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaInicioPropertyChange(evt);
            }
        });

        FechaFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaFinalPropertyChange(evt);
            }
        });

        btnRecargar.setText("Recargar tabla");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addGap(0, 365, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdelante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seguimiento)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdelante)
                    .addComponent(btnAtras)
                    .addComponent(seguimiento))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        String textoBusqueda = txtBusqueda.getText();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String textoInicial;
        String textoFinal;
               try {
                    textoFinal = formato.format(FechaFinal.getDate());
               } catch (Exception e) {
                    textoFinal = null;
               }
                try {
                    textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
               } catch (Exception e) {
                    textoInicial = null;
               }
        paginaActual = 1;
        totalPages = Devoluciones.NumeroPages(textoBusqueda, textoInicial, textoFinal);
        Devoluciones.MostrarDevoluciones(textoBusqueda, paginaActual, totalPages, textoInicial, textoFinal);
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusGained
        // TODO add your handling code here:
        //placeholder para notificar como realizar la busqueda
        JTextField textField = (JTextField) evt.getSource();
        String placeholder = "Buscar por la fecha, por descripción y por el número de factura";

        if (textField.getText().equals(placeholder)) {
            textField.setText("");
            textField.setForeground(Color.BLACK); // Establece el color de fuente adecuado
        }
    }//GEN-LAST:event_txtBusquedaFocusGained

    private void txtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusLost
        // TODO add your handling code here:
        //placeholder para notificar como realizar la busqueda
          JTextField textField = (JTextField) evt.getSource();
          String placeholder = "Buscar por la fecha, por descripción y por el número de factura";

          if (textField.getText().isEmpty()) {
            textField.setText(placeholder);
            textField.setForeground(Color.GRAY); // Establece el color de fuente del placeholder
          }
    }//GEN-LAST:event_txtBusquedaFocusLost

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String textoBusqueda = txtBusqueda.getText();
        String textoInicial;
        String textoFinal;
               try {
                    textoFinal = formato.format(FechaFinal.getDate());
               } catch (Exception e) {
                    textoFinal = null;
               }
                try {
                    textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
               } catch (Exception e) {
                    textoInicial = null;
               }
        if (paginaActual > 1) {
            paginaActual--;
            Devoluciones.MostrarDevoluciones(textoBusqueda, paginaActual, totalPages, textoInicial, textoFinal);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String textoBusqueda = txtBusqueda.getText();
        String textoInicial;
        String textoFinal;
               try {
                    textoFinal = formato.format(FechaFinal.getDate());
               } catch (Exception e) {
                    textoFinal = null;
               }
                try {
                    textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
               } catch (Exception e) {
                    textoInicial = null;
               }
        if (paginaActual < totalPages) {
            paginaActual++;
            Devoluciones.MostrarDevoluciones(textoBusqueda, paginaActual, totalPages, textoInicial, textoFinal);
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed
    
    
    private void tblMostrarDevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarDevolucionesMouseClicked
        
        if (evt.getClickCount() == 2) {
        int fila = tblMostrarDevoluciones.getSelectedRow();

        if (fila != -1) { // Asegura que se haya seleccionado una fila
            String id = tblMostrarDevoluciones.getValueAt(fila, 8).toString();
            String idVentas = tblMostrarDevoluciones.getValueAt(fila, 9).toString();
            String monto_a_devolver = tblMostrarDevoluciones.getValueAt(fila, 7).toString();

            VerDevoluciones verDevoluciones = new VerDevoluciones(id, idVentas, monto_a_devolver);

            // Configura otros componentes en VerDevoluciones según sea necesario
            verDevoluciones.txtDescripcion.setText(tblMostrarDevoluciones.getValueAt(fila, 2).toString());
            verDevoluciones.lblFecha1.setText(tblMostrarDevoluciones.getValueAt(fila, 3).toString());

            verDevoluciones.setVisible(true);
        }
    }
    }//GEN-LAST:event_tblMostrarDevolucionesMouseClicked

    private void FechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaInicioPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String textoBusqueda = txtBusqueda.getText();
            String textoInicial;
            String textoFinal;
            try {
                textoFinal = formato.format(FechaFinal.getDate());
            } catch (Exception e) {
                textoFinal = null;
            }
            try {
                textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
            } catch (Exception e) {
                textoInicial = null;
            }
//            System.out.println(textoInicial);
//            System.out.println(textoFinal);

            paginaActual = 1;
            totalPages = Devoluciones.NumeroPages(textoBusqueda,textoInicial,textoFinal);
            Devoluciones.MostrarDevoluciones(textoBusqueda, paginaActual, totalPages,textoInicial,textoFinal);
        }

    }//GEN-LAST:event_FechaInicioPropertyChange

    private void FechaFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaFinalPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String textoBusqueda = txtBusqueda.getText();
            String textoInicial;
            String textoFinal;
            try {
                textoFinal = formato.format(FechaFinal.getDate());
            } catch (Exception e) {
                textoFinal = null;
            }
            try {
                textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
            } catch (Exception e) {
                textoInicial = null;
            }
//            System.out.println(textoInicial);
//            System.out.println(textoFinal);

            paginaActual = 1;
            totalPages = Devoluciones.NumeroPages(textoBusqueda,textoInicial,textoFinal);
            Devoluciones.MostrarDevoluciones(textoBusqueda, paginaActual, totalPages,textoInicial,textoFinal);
        }
    }//GEN-LAST:event_FechaFinalPropertyChange

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        FechaInicio.setDate(null);    
        FechaFinal.setDate(null);    
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String textoInicial;
            String textoFinal;
               try {
                    textoFinal = formato.format(FechaFinal.getDate());
               } catch (Exception e) {
                    textoFinal = null;
               }
                try {
                    textoInicial = formato.format(FechaInicio.getDateEditor().getDate());
               } catch (Exception e) {
                    textoInicial = null;
               }
        Devoluciones.MostrarDevoluciones("", paginaActual, totalPages, textoInicial, textoFinal);
    }//GEN-LAST:event_btnRecargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaFinal;
    private com.toedter.calendar.JDateChooser FechaInicio;
    public static javax.swing.JButton btnAdelante;
    public static javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel seguimiento;
    public static javax.swing.JTable tblMostrarDevoluciones;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
